language: go
sudo: false
go:
  - 1.9
  - tip
install:
  - make setup
script:
  - make test
  - make check
  - make cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
notifications:
  on_success: never # default: change
  on_failure: change # default: always
